In [1]:
import torch
import numpy as np

In [2]:
a = torch.FloatTensor(3, 2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [3]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
torch.FloatTensor([[1,2,3],[3,2,1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [5]:
n = np.zeros(shape=(3, 2), dtype=np.float32)
b = torch.tensor(n, dtype=torch.int64)
b

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [6]:
a = torch.tensor([1,2,3])
s = a.sum()
s

tensor(6)

In [11]:
print(type(s.item()))
print(type(s))

<class 'int'>
<class 'torch.Tensor'>


In [14]:
a = torch.FloatTensor([2,3])
ca = a.to('cuda'); ca

AssertionError: Torch not compiled with CUDA enabled